TARGET := iphone:clang:latest:16.0
ARCHS := arm64

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME := MoonPlace

MoonPlace_FILES = BotCompat/main.m BotCompat/AppDelegate.m BotCompat/ViewController.m BotCompat/CleanerViewController.m BotCompat/SettingsViewController.m BotCompat/Localization.m BotCompat/CommonCryptoCompat.m BotCompat/BuiltInAIM.m BotCompat/PatchCore.m BotCompat/PatchProjectsViewController.m BotCompat/FilesViewController.m BotCompat/SandboxAccessBridge.m BotCompat/ExploitCompatibility.m BotCompat/bad_query.c BotCompat/mcm_bridge.m ThreeOneOSFive/exploit/zip_extract.c ThreeOneOSFive/helpers/AntiDetection.m ThreeOneOSFive/helpers/AppIconHelper.m ThreeOneOSFive/helpers/DisplayIdentity.m ThreeOneOSFive/kexploit/kexploit_opa334.m ThreeOneOSFive/kexploit/krw.m ThreeOneOSFive/kexploit/kutils.m ThreeOneOSFive/kexploit/offsets.m ThreeOneOSFive/kexploit/sandbox_escape.m ThreeOneOSFive/kexploit/vnode.m ThreeOneOSFive/App.swift ThreeOneOSFive/ContentView.swift ThreeOneOSFive/Views/MoonWelcomeView.swift ThreeOneOSFive/Views/MoonLoginView.swift ThreeOneOSFive/Views/MoonLoginComponents.swift ThreeOneOSFive/Views/MoonPlaceView.swift ThreeOneOSFive/Views/PatchModeView.swift ThreeOneOSFive/Views/PatchOptionRow.swift ThreeOneOSFive/Views/OnboardingView.swift ThreeOneOSFive/Views/DesignSystem.swift ThreeOneOSFive/Views/CleanerView.swift ThreeOneOSFive/Views/FileBrowserView.swift ThreeOneOSFive/Views/FilesView.swift ThreeOneOSFive/Views/FolderPatchSelectionView.swift ThreeOneOSFive/Views/LogView.swift ThreeOneOSFive/Views/PatchProjectEditorView.swift ThreeOneOSFive/Views/PatchProjectsView.swift ThreeOneOSFive/Views/SettingsView.swift ThreeOneOSFive/Helpers/MoonAuthManager.swift ThreeOneOSFive/Helpers/DevicePatchService.swift ThreeOneOSFive/Helpers/PatchProjectStore.swift ThreeOneOSFive/Helpers/Utils.swift ThreeOneOSFive/Helpers/ZIPArchiveExtractor.swift ThreeOneOSFive/Helpers/ZIPArchiveWriter.swift

MoonPlace_FRAMEWORKS = UIKit Foundation UniformTypeIdentifiers IOSurface Security SwiftUI
MoonPlace_CFLAGS = -fobjc-arc -IBotCompat -IThreeOneOSFive -IThreeOneOSFive/exploit -IThreeOneOSFive/kexploit -IThreeOneOSFive/helpers
MoonPlace_RESOURCE_FILES = ThreeOneOSFive/Resources/ExternalIcon.png ThreeOneOSFive/Resources/FF/APOST.3105 ThreeOneOSFive/Resources/FF/ASSIST.3105 ThreeOneOSFive/Resources/FF/DRAG.3105 ThreeOneOSFive/Resources/FF/NECK.3105 ThreeOneOSFive/Resources/FF/BODY_DISGUISED.3105 ThreeOneOSFive/Resources/FF/REMOVE_AIMS_FF.3105 ThreeOneOSFive/Resources/FF/120-144_FPS.3105 ThreeOneOSFive/Resources/FF/REMOVE_FPS.3105 ThreeOneOSFive/Resources/FF/TRICK.3105 ThreeOneOSFive/Resources/FF2022/FF2022_ASSIST.3105 ThreeOneOSFive/Resources/FF2022/FF2022_DRAG.3105 ThreeOneOSFive/Resources/FF2022/FF2022_NECK.3105 ThreeOneOSFive/Resources/FF2022/FF2022_CHEST_100.3105 ThreeOneOSFive/Resources/FF2022/FF2022_VECTORED.3105 ThreeOneOSFive/Resources/FF2022/FF2022_SILENT.3105 ThreeOneOSFive/Resources/FF2022/FF2022_REMOVE_AIMS.3105 ThreeOneOSFive/en.lproj/Localizable.strings ThreeOneOSFive/Info.plist

include $(THEOS_MAKE_PATH)/application.mk